comment verbose logging in conf
tcpcloud/salt-formula-mongodb pull request #1
Opened 2016-10-25 14:37 UTC by epcim

comment verbose logging in conf, mongo is very talk active and generates GB on this mode

2016-10-25 14:40 UTC, fpytloun requested changes

2016-10-25 14:40 UTC, fpytloun commented on mongodb/files/mongodb.conf
> +# verbose = true
Make it configurable and keep default.

2016-10-25 16:37 UTC, epcim commented on mongodb/files/mongodb.conf
> +# verbose = true
This option is not to set log verbosity, this is switch to enable maximum logging. To set logging level there is an `oplog` attribute that is not managed and there is no reasoning to work on that as newer version uses different configuration structure at all.

This PR is hotfix.

Verbose (true/false) should be by default switched off. There is no reason to make this configurable as it's used only for manual debugging.

Newer version of mongodb  uses different configuration files, new style is not even compatible with the current options - so attribute model would not fit anyway: https://docs.mongodb.com/manual/reference/configuration-options/#systemlog-options

2016-10-26 12:20 UTC, fpytloun commented on mongodb/files/mongodb.conf
> +verbose = {{ server.logging.get('verbose', 'false') }}
Use this:
```
{{ server.logging.get('verbose', False)|lower }}
```

2017-05-03 08:46 UTC, merged